# Text Mining

In [ ]:
import pandas as pd

## Lectura de datos

In [ ]:
df = pd.read_excel('comentarios_parrilas.csv.xlsx')
df.shape

(21544, 4)

In [ ]:
df.head()

,comida,servicio,ambiente,comentario
0,0.0,1.0,1.0,"no fue todo malo, pedi 1 chori 1 morci bien ..."
1,3.0,3.0,3.0,"Buenas tardes, alguien podría decirme si en la..."
2,3.0,3.0,3.0,"Hiper recomendable. La atención es lenta, pero..."
3,3.0,3.0,2.0,Fuimos un viernes por la noche. Repleto de gen...
4,3.0,2.0,2.0,"Cómo siempre el Mejor Lechón, se Cortaba con s..."

In [ ]:
df = df.sample(100)

## Minúsculas

In [ ]:
df['comentario'] = df['comentario'].str.lower()
df.head()

,comida,servicio,ambiente,comentario
8119,2.0,1.0,1.0,sin duda el mayor esfuerzo esta en la comida q...
2036,2.0,1.0,3.0,bastante caro
8758,1.0,1.0,2.0,me sorprendió por la cantidad de gente que hab...
3475,1.0,2.0,2.0,"comimos muy bien! el pan es estupendo, imposib..."
4418,3.0,2.0,3.0,muy buena atencion! un mozo siempre atento a s...

## Spacy

In [ ]:
import spacy

import locale
locale.getpreferredencoding = lambda: "UTF-8"

In [ ]:
! spacy download es_core_news_sm

Collecting es-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.8.0/es_core_news_sm-3.8.0-py3-none-any.whl (12.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 77.3 MB/s eta 0:00:00
Installing collected packages: es-core-news-sm
Successfully installed es-core-news-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('es_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
nlp = spacy.load("es_core_news_sm")

## Tokenizador

In [ ]:
doc = nlp(df.iloc[3].comentario)
print(doc.text)
for token in doc:
    print(token.text, "-->", token.pos_)

comimos muy bien! el pan es estupendo, imposible parar de comer. de entrada comimos \"ruculeta\", excelente combinación de sabores. los platos muy bien presentados, bastante generosas las porciones y servidos en su punto justo. muy buena elección! lo recomiendo! para volver...
comimos --> VERB
muy --> ADV
bien --> ADV
! --> PUNCT
el --> DET
pan --> NOUN
es --> AUX
estupendo --> VERB
, --> PUNCT
imposible --> ADJ
parar --> VERB
de --> ADP
comer --> VERB
. --> PUNCT
de --> ADP
entrada --> NOUN
comimos --> ADJ
\"ruculeta\ --> ADJ
" --> PUNCT
, --> PUNCT
excelente --> ADJ
combinación --> NOUN
de --> ADP
sabores --> NOUN
. --> PUNCT
los --> DET
platos --> NOUN
muy --> ADV
bien --> ADV
presentados --> ADJ
, --> PUNCT
bastante --> ADV
generosas --> ADJ
las --> DET
porciones --> NOUN
y --> CCONJ
servidos --> ADJ
en --> ADP
su --> DET
punto --> NOUN
justo --> ADJ
. --> PUNCT
muy --> ADV
buena --> ADJ
elección --> NOUN
! --> PUNCT
lo --> PRON
recomiendo --> VERB
! --> PUNCT
para --> ADP
volver --> VERB
... --> PUNCT

In [ ]:
df['comentario_tok'] = df['comentario'].apply(lambda texto: [token.text for token in nlp(texto)])
df['comentario_tok']

8119     [sin, duda, el, mayor, esfuerzo, esta, en, la,...
2036                                      [bastante, caro]
8758     [me, sorprendió, por, la, cantidad, de, gente,...
3475     [comimos, muy, bien, !, el, pan, es, estupendo...
4418     [muy, buena, atencion, !, un, mozo, siempre, a...
                               ...
19048    [riquisimo, !, !, !, impecable, !, atención, ,...
17963    [un, lugar, muy, agradable, ., la, parrilla, e...
7902     [fuimos, el, viernes, pasado, ,, la, carne, ma...
5723     [la, atención, de, la, moza, súper, buena, ,, ...
7750     [gran, relación, calidad, /, cantidad, /, prec...
Name: comentario_tok, Length: 100, dtype: object

## Lematizador

In [ ]:
doc = nlp(df.iloc[2].comentario)
print(doc.text)
for token in doc:
    print(token.text, "-->", token.lemma_)

me sorprendió por la cantidad de gente que había, lo rápido que salió la comida, la buena atención y la calidad de la comida. muy recomendable. la única contra es que hay que ir temprano o hay que esperar.
me --> yo
sorprendió --> sorprender
por --> por
la --> el
cantidad --> cantidad
de --> de
gente --> gente
que --> que
había --> haber
, --> ,
lo --> él
rápido --> rápido
que --> que
salió --> salir
la --> el
comida --> comida
, --> ,
la --> el
buena --> buen
atención --> atención
y --> y
la --> el
calidad --> calidad
de --> de
la --> el
comida --> comida
. --> .
muy --> mucho
recomendable --> recomendable
. --> .
la --> el
única --> único
contra --> contra
es --> ser
que --> que
hay --> haber
que --> que
ir --> ir
temprano --> temprano
o --> o
hay --> haber
que --> que
esperar --> esperar
. --> .

In [ ]:
df['comentario_tok'] = df['comentario'].apply(lambda texto: [token.lemma_ for token in nlp(texto)])
df['comentario_tok']

8119     [sin, duda, el, mayor, esfuerzo, este, en, el,...
2036                                      [bastante, caro]
8758     [yo, sorprender, por, el, cantidad, de, gente,...
3475     [comer, mucho, bien, !, el, pan, ser, estupend...
4418     [mucho, buen, atencion, !, uno, mozo, siempre,...
                               ...
19048    [riquisimo, !, !, !, impecable, !, atención, ,...
17963    [uno, lugar, mucho, agradable, ., el, parrilla...
7902     [ir, el, viernes, pasado, ,, el, carne, malo, ...
5723     [el, atención, de, el, moza, súper, buen, ,, m...
7750     [gran, relación, calidad, /, cantidad, /, prec...
Name: comentario_tok, Length: 100, dtype: object

## Normalización

In [ ]:
m = {'morci': 'morcilla', 'chori': 'chorizo', 'muuuuy': 'muy'}

df['comentario_tok'] = df['comentario_tok'].apply(lambda texto: [m.get(token, token) for token in texto])
df['comentario_tok']

8119     [sin, duda, el, mayor, esfuerzo, este, en, el,...
2036                                      [bastante, caro]
8758     [yo, sorprender, por, el, cantidad, de, gente,...
3475     [comer, mucho, bien, !, el, pan, ser, estupend...
4418     [mucho, buen, atencion, !, uno, mozo, siempre,...
                               ...
19048    [riquisimo, !, !, !, impecable, !, atención, ,...
17963    [uno, lugar, mucho, agradable, ., el, parrilla...
7902     [ir, el, viernes, pasado, ,, el, carne, malo, ...
5723     [el, atención, de, el, moza, súper, buen, ,, m...
7750     [gran, relación, calidad, /, cantidad, /, prec...
Name: comentario_tok, Length: 100, dtype: object

In [ ]:
df['comentario_tok'] = df['comentario_tok'].apply(lambda texto: [token for token in texto if token not in (":", ",", ".", "!")])
df['comentario_tok']

8119     [sin, duda, el, mayor, esfuerzo, este, en, el,...
2036                                      [bastante, caro]
8758     [yo, sorprender, por, el, cantidad, de, gente,...
3475     [comer, mucho, bien, el, pan, ser, estupendo, ...
4418     [mucho, buen, atencion, uno, mozo, siempre, at...
                               ...
19048    [riquisimo, impecable, atención, comida, y, am...
17963    [uno, lugar, mucho, agradable, el, parrilla, s...
7902     [ir, el, viernes, pasado, el, carne, malo, est...
5723     [el, atención, de, el, moza, súper, buen, muys...
7750     [gran, relación, calidad, /, cantidad, /, prec...
Name: comentario_tok, Length: 100, dtype: object

## Stopwords

In [ ]:
stopwords = nlp.Defaults.stop_words
stopwords

{'a',
 'acuerdo',
 'adelante',
 'ademas',
 'además',
 'afirmó',
 'agregó',
 'ahi',
 'ahora',
 'ahí',
 'al',
 'algo',
 'alguna',
 'algunas',
 'alguno',
 'algunos',
 'algún',
 'alli',
 'allí',
 'alrededor',
 'ambos',
 'ante',
 'anterior',
 'antes',
 'apenas',
 'aproximadamente',
 'aquel',
 'aquella',
 'aquellas',
 'aquello',
 'aquellos',
 'aqui',
 'aquél',
 'aquélla',
 'aquéllas',
 'aquéllos',
 'aquí',
 'arriba',
 'aseguró',
 'asi',
 'así',
 'atras',
 'aun',
 'aunque',
 'añadió',
 'aún',
 'bajo',
 'bastante',
 'bien',
 'breve',
 'buen',
 'buena',
 'buenas',
 'bueno',
 'buenos',
 'cada',
 'casi',
 'cierta',
 'ciertas',
 'cierto',
 'ciertos',
 'cinco',
 'claro',
 'comentó',
 'como',
 'con',
 'conmigo',
 'conocer',
 'conseguimos',
 'conseguir',
 'considera',
 'consideró',
 'consigo',
 'consigue',
 'consiguen',
 'consigues',
 'contigo',
 'contra',
 'creo',
 'cual',
 'cuales',
 'cualquier',
 'cuando',
 'cuanta',
 'cuantas',
 'cuanto',
 'cuantos',
 'cuatro',
 'cuenta',
 'cuál',
 'cuáles',
 'cuándo',
 'cuánta',
 'cuántas',
 'cuánto',
 'cuántos',
 'cómo',
 'da',
 'dado',
 'dan',
 'dar',
 'de',
 'debajo',
 'debe',
 'deben',
 'debido',
 'decir',
 'dejó',
 'del',
 'delante',
 'demasiado',
 'demás',
 'dentro',
 'deprisa',
 'desde',
 'despacio',
 'despues',
 'después',
 'detras',
 'detrás',
 'dia',
 'dias',
 'dice',
 'dicen',
 'dicho',
 'dieron',
 'diez',
 'diferente',
 'diferentes',
 'dijeron',
 'dijo',
 'dio',
 'doce',
 'donde',
 'dos',
 'durante',
 'día',
 'días',
 'dónde',
 'e',
 'el',
 'ella',
 'ellas',
 'ello',
 'ellos',
 'embargo',
 'en',
 'encima',
 'encuentra',
 'enfrente',
 'enseguida',
 'entonces',
 'entre',
 'era',
 'eramos',
 'eran',
 'eras',
 'eres',
 'es',
 'esa',
 'esas',
 'ese',
 'eso',
 'esos',
 'esta',
 'estaba',
 'estaban',
 'estado',
 'estados',
 'estais',
 'estamos',
 'estan',
 'estar',
 'estará',
 'estas',
 'este',
 'esto',
 'estos',
 'estoy',
 'estuvo',
 'está',
 'están',
 'excepto',
 'existe',
 'existen',
 'explicó',
 'expresó',
 'fin',
 'final',
 'fue',
 'fuera',
 'fueron',
 'fui',
 'fuimos',
 'gran',
 'grande',
 'grandes',
 'ha',
 'haber',
 'habia',
 'habla',
 'hablan',
 'habrá',
 'había',
 'habían',
 'hace',
 'haceis',
 'hacemos',
 'hacen',
 'hacer',
 'hacerlo',
 'haces',
 'hacia',
 'haciendo',
 'hago',
 'han',
 'hasta',
 'hay',
 'haya',
 'he',
 'hecho',
 'hemos',
 'hicieron',
 'hizo',
 'hoy',
 'hubo',
 'igual',
 'incluso',
 'indicó',
 'informo',
 'informó',
 'ir',
 'junto',
 'la',
 'lado',
 'largo',
 'las',
 'le',
 'les',
 'llegó',
 'lleva',
 'llevar',
 'lo',
 'los',
 'luego',
 'mal',
 'manera',
 'manifestó',
 'mas',
 'mayor',
 'me',
 'mediante',
 'medio',
 'mejor',
 'mencionó',
 'menos',
 'menudo',
 'mi',
 'mia',
 'mias',
 'mientras',
 'mio',
 'mios',
 'mis',
 'misma',
 'mismas',
 'mismo',
 'mismos',
 'modo',
 'mucha',
 'muchas',
 'mucho',
 'muchos',
 'muy',
 'más',
 'mí',
 'mía',
 'mías',
 'mío',
 'míos',
 'nada',
 'nadie',
 'ni',
 'ninguna',
 'ningunas',
 'ninguno',
 'ningunos',
 'ningún',
 'no',
 'nos',
 'nosotras',
 'nosotros',
 'nuestra',
 'nuestras',
 'nuestro',
 'nuestros',
 'nueva',
 'nuevas',
 'nueve',
 'nuevo',
 'nuevos',
 'nunca',
 'o',
 'ocho',
 'once',
 'os',
 'otra',
 'otras',
 'otro',
 'otros',
 'para',
 'parece',
 'parte',
 'partir',
 'pasada',
 'pasado',
 'paìs',
 'peor',
 'pero',
 'pesar',
 'poca',
 'pocas',
 'poco',
 'pocos',
 'podeis',
 'podemos',
 'poder',
 'podria',
 'podriais',
 'podriamos',
 'podrian',
 'podrias',
 'podrá',
 'podrán',
 'podría',
 'podrían',
 'poner',
 'por',
 'porque',
 'posible',
 'primer',
 'primera',
 'primero',
 'primeros',
 'pronto',
 'propia',
 'propias',
 'propio',
 'propios',
 'proximo',
 'próximo',
 'próximos',
 'pudo',
 'pueda',
 'puede',
 'pueden',
 'puedo',
 'pues',
 'qeu',
 'que',
 'quedó',
 'queremos',
 'quien',
 'quienes',
 'quiere',
 'quiza',
 'quizas',
 'quizá',
 'quizás',
 'quién',
 'quiénes',
 'qué',
 'realizado',
 'realizar',
 'realizó',
 'repente',
 'respecto',
 'sabe',
 'sabeis',
 'sabemos',
 'saben',
 'saber',
 'sabes',
 'salvo',
 'se',
 'sea',
 'sean',
 'segun',
 'segunda',
 'segundo',
 'según',
 'seis',
 'ser',
 'sera',
 'será',
 'serán',
 'sería',
 'señaló',
 'si',
 'sido',
 'siempre',
 'siendo',
 'siete',
 'sigue',
 'siguiente',
 'sin',
 'sino',
 'sobre',
 'sois',
 'sola',
 'solamente',
 'solas',
 'solo',
 'solos',
 'somos',
 'son',
 'soy',
 'su',
 'supuesto',
 'sus',
 'suya',
 'suyas',
 'suyo',
 'suyos',
 'sé',
 'sí',
 'sólo',
 'tal',
 'tambien',
 'también',
 'tampoco',
 'tan',
 'tanto',
 'tarde',
 'te',
 'temprano',
 'tendrá',
 'tendrán',
 'teneis',
 'tenemos',
 'tener',
 'tenga',
 'tengo',
 'tenido',
 'tenía',
 'tercera',
 'tercero',
 'ti',
 'tiene',
 'tienen',
 'toda',
 'todas',
 'todavia',
 'todavía',
 'todo',
 'todos',
 'total',
 'tras',
 'trata',
 'través',
 'tres',
 'tu',
 'tus',
 'tuvo',
 'tuya',
 'tuyas',
 'tuyo',
 'tuyos',
 'tú',
 'u',
 'ultimo',
 'un',
 'una',
 'unas',
 'uno',
 'unos',
 'usa',
 'usais',
 'usamos',
 'usan',
 'usar',
 'usas',
 'uso',
 'usted',
 'ustedes',
 'va',
 'vais',
 'vamos',
 'van',
 'varias',
 'varios',
 'vaya',
 'veces',
 'ver',
 'verdad',
 'verdadera',
 'verdadero',
 'vez',
 'vosotras',
 'vosotros',
 'voy',
 'vuestra',
 'vuestras',
 'vuestro',
 'vuestros',
 'y',
 'ya',
 'yo',
 'él',
 'ésa',
 'ésas',
 'ése',
 'ésos',
 'ésta',
 'éstas',
 'éste',
 'éstos',
 'última',
 'últimas',
 'último',
 'últimos'}

In [ ]:
stopwords.update(['es', 'osea', 'sólo', 'la', 'el', 'los', 'las'])

df['comentario_tok'] = df['comentario_tok'].apply(lambda texto: [token for token in texto if token not in stopwords])
df['comentario_tok']

8119     [duda, esfuerzo, comida, servir, parrilla, (, ...
2036                                                [caro]
8758     [sorprender, cantidad, gente, rápido, salir, c...
3475     [comer, pan, estupendo, imposible, parar, come...
4418     [atencion, mozo, atento, servir, agua, venir, ...
                               ...
19048    [riquisimo, impecable, atención, comida, ambie...
17963    [lugar, agradable, parrilla, porción, abundant...
7902     [viernes, carne, malo, marcado, seco, atención...
5723     [atención, moza, súper, muysimpático, sonrisa,...
7750     [relación, calidad, /, cantidad, /, precio, se...
Name: comentario_tok, Length: 100, dtype: object

## Preparación para predicción

In [ ]:
df['comentario'] = df['comentario_tok'].str.join(' ')
df['comentario']

8119     duda esfuerzo comida servir parrilla ( zona ) ...
2036                                                  caro
8758     sorprender cantidad gente rápido salir comida ...
3475     comer pan estupendo imposible parar comer entr...
4418     atencion mozo atento servir agua venir veiar c...
                               ...
19048    riquisimo impecable atención comida ambiente i...
17963    lugar agradable parrilla porción abundante amb...
7902     viernes carne malo marcado seco atención mozo ...
5723     atención moza súper muysimpático sonrisa orien...
7750     relación calidad / cantidad / precio seguir vo...
Name: comentario, Length: 100, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(ngram_range=(1, 3), min_df=0.005, max_df=0.7, strip_accents='ascii', max_features=2000)
vectorized_data = vectorizer.fit_transform(df['comentario'])
vectorized_data.toarray()

array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vectorizer.get_feature_names_out().tolist()

['03 precio',
 '03 precio pagina',
 '10',
 '10 comida',
 '10 comida impredible',
 '10 persona',
 '10 persona olvidar',
 '100',
 '100 bodegon',
 '100 bodegon boedo',
 '100 recomendable',
 '1000',
 '1000 desilusionir',
 '1000 desilusionir predisponir',
 '107',
 '200',
 '21',
 '23',
 '60',
 'abundante',
 'abundante compartir',
 'abundante precio',
 'aceptable',
 'achura',
 'acorde',
 'acorde lugar',
 'agradable',
 'agua',
 'alguien sacar',
 'alguien sacar cantidad',
 'algun',
 'algun plato',
 'algun plato caliente',
 'almorzar',
 'almorzar esposa',
 'almorzar esposa intentar',
 'although',
 'although the',
 'although the portions',
 'alto',
 'alto chimichurri',
 'alto falta',
 'alto falta luz',
 'alto loco',
 'alto loco lugar',
 'amable',
 'amable atento',
 'amable atento tano',
 'amable servicial',
 'ambeintado',
 'ambeintado separacion',
 'ambeintado separacion mesa',
 'ambien',
 'ambien ok',
 'ambien ok cerca',
 'ambientacion',
 'ambientacion tipo',
 'ambientacion tipo bodegon',
 'ambientar',
 'ambientar regular',
 'ambientar regular no',
 'ambiente',
 'ambiente agradable',
 'ambiente agradable faltar',
 'ambiente ameno',
 'ambiente ameno atencion',
 'ambiente carne',
 'ambiente carne probar',
 'ambiente chico',
 'ambiente chico calido',
 'ambiente compensar',
 'ambiente compensar atencion',
 'ambiente deberio',
 'ambiente deberio mejorar',
 'ambiente excelente',
 'ambiente excelente personal',
 'ambiente familiar',
 'ambiente familiar atencion',
 'ambiente festivo',
 'ambiente festivo amigo',
 'ambiente formal',
 'ambiente gustar',
 'ambiente gustar gente',
 'ambiente ideal',
 'ambiente ideal amigo',
 'ambiente ideal familia',
 'ambiente insuperabl',
 'ambiente lamentablemente',
 'ambiente lamentablemente esperar',
 'ambiente ruidoso',
 'ambiente ruidoso comentar',
 'ambiente servicio',
 'ambiente servicio apreciable',
 'ambiente tenso',
 'ambiente tenso iluminacion',
 'ambiente tranquilo',
 'ambiente tranquilo agradable',
 'ambiente tranquilo mesa',
 'ameno',
 'ameno atencion',
 'ameno atencion personal',
 'ameno musica',
 'ameno musica atencion',
 'amiga',
 'amiga comimos',
 'amiga comimos podiar',
 'amigo',
 'amigo amigo',
 'amigo amigo resumir',
 'amigo comer',
 'amigo comer gastar',
 'amigo famila',
 'amigo famila entrada',
 'amigo familia',
 'amigo familia numeroso',
 'amigo pedi',
 'amigo pedi parrillado',
 'amigo principal',
 'amigo principal comar',
 'amigo resumir',
 'amigo resumir poco',
 'amigo servicio',
 'amigo servicio podrio',
 'ampliar',
 'ampliar horario',
 'ampliar horario reserva',
 'amplificar',
 'amplificar ruido',
 'amplificar ruido haciendolo',
 'amplio',
 'amplio comida',
 'amplio comida rico',
 'amplio variedad',
 'amplio variedad carta',
 'and',
 'and atmospherir',
 'and atmospherir the',
 'and helpful',
 'and the',
 'and the waiters',
 'andino',
 'andino papin',
 'andino papin papa',
 'anfitrion',
 'anfitrion gana',
 'anfitrion gana regresar',
 'aniversario',
 'aniversario plato',
 'aniversario plato excelente',
 'ano',
 'ano esposa',
 'ano esposa cenar',
 'ano practicamnete',
 'ano practicamnete extension',
 'anotar',
 'anotar comida',
 'anotar comida sabroso',
 'antipasto',
 'antipasto ravello',
 'antipasto ravello sorrentino',
 'aparte',
 'aparte hay',
 'aparte hay estacionamiento',
 'aperitivo',
 'aperitivo llegar',
 'aperitivo llegar champagne',
 'apreciable',
 'apreciable casualidad',
 'apreciable casualidad tocar',
 'apriet',
 'apriet frente',
 'apriet frente asu',
 'aprovechar',
 'aprovechar precio',
 'aprovechar precio ubicacion',
 'are',
 'are bit',
 'are bit on',
 'are smaller',
 'are smaller than',
 'argentino',
 'argentino desastre',
 'argentino desastre atencion',
 'argento',
 'argento tierno',
 'argento tierno sabroso',
 'asada',
 'asado',
 'asado cortir',
 'asado cortir cuchara',
 'asado genial',
 'asado genial vino',
 'asado lechon',
 'asado lechon perfectamente',
 'asado vacio',
 'asado vacio reclamar',
 'asimismo',
 'asimismo gomosa',
 'asimismo gomosa traer',
 'aspecto',
 'aspecto destacar',
 'aspecto destacar sentar',
 'asu',
 'asu local',
 'asu local persona',
 'atencion',
 'atencion 10',
 'atencion 10 comida',
 'atencion 60',
 'atencion 60 minuto',
 'atencion ambiente',
 'atencion ambiente carne',
 'atencion ambiente chico',
 'atencion barbara',
 'atencion barbara esposa',
 'atencion calidad',
 'atencion calidad comida',
 'atencion caro',
 'atencion caro malo',
 'atencion cobrar',
 'atencion cobrar servicio',
 'atencion comar',
 'atencion comar precio',
 'atencion comida',
 'atencion comida ambiente',
 'atencion cordial',
 'atencion cordial profesional',
 'atencion correcto',
 'atencion correcto menu',
 'atencion costo',
 'atencion costo comer',
 'atencion desordenado',
 'atencion desordenado variedad',
 'atencion destacable',
 'atencion destacable lugar',
 'atencion dueno',
 'atencion dueno sentado',
 'atencion inmejorable',
 'atencion inmejorable precio',
 'atencion juntar',
 'atencion juntar exquisitez',
 'atencion lugar',
 'atencion lugar lleno',
 'atencion maravilloso',
 'atencion maravilloso carne',
 'atencion moza',
 'atencion moza super',
 'atencion mozar',
 'atencion mozar diligente',
 'atencion mozo',
 'atencion mozo ambiente',
 'atencion mozo atento',
 'atencion mozo carne',
 'atencion normal',
 'atencion normal faltar',
 'atencion parrilla',
 'atencion parrilla pedir',
 'atencion personal',
 'atencion personal comida',
 'atencion precio',
 'atencion precio razonable',
 'atencion rapido',
 'atencion recomeir',
 'atencion recomeir 100',
 'atencion servicio',
 'atencion servicio pesimo',
 'atencion temperatura',
 'atencion temperatura comida',
 'atencion ves',
 'atencion ves regular',
 'atender',
 'atender barbaro',
 'atender hotel',
 'atender hotel visitar',
 'atenderno',
 'atenderno prender',
 'atenderno prender vela',
 'atendido',
 'atendido chica',
 'atendido chica simpatico',
 'atentar',
 'atentar servicio',
 'atentar servicio esperar',
 'atento',
 'atento carne',
 'atento carne abundante',
 'atento copa',
 'atento copa tomar',
 'atento excelente',
 'atento excelente comida',
 'atento servir',
 'atento servir agua',
 'atento tano',
 'atento tano dueno',
 'atmospherir',
 'atmospherir the',
 'atmospherir the food',
 'auto',
 'auto deber',
 'auto deber pagar',
 'auto frente',
 'auto frente restaurante',
 'average',
 'average child',
 'average child portion',
 'avis',
 'avis zona',
 'ayer',
 'ayer 21',
 'ayer 21 03',
 'ayer persona',
 'ayer persona provoleta',
 'ayudante',
 'ayudante parrilla',
 'ayudante parrilla tardar',
 'ayudar',
 'ayudar decidir',
 'ayudar decidir sugerir',
 'bajar',
 'bajar calidad',
 'bajo',
 'bajo postre',
 'bajo postre cafe',
 'bar',
 'bar surtido',
 'bar surtido suficiente',
 'barato',
 'barato ambiente',
 'barato ambiente compensar',
 'barato comer',
 'barbara',
 'barbara esposa',
 'barbara esposa plato',
 'barbaro',
 'barra',
 'barraca',
 'barraca recomendable',
 'barrio',
 'barrio chiquita',
 'barrio chiquita rico',
 'bebida',
 'bebida libre',
 'bebida libre entender',
 'bebida litro',
 'bebida litro postre',
 'bebida postre',
 'bebida postre volver',
 'bife',
 'bife aged',
 'bife aged ensalada',
 'bife chorizo',
 'bife chorizo argento',
 'bife chorizo duro',
 'bife chorizo especial',
 'bife chorizo venir',
 'bife excelente',
 'bife excelente calidad',
 'bife lomo',
 'bife lomo agua',
 'bife lomo comi',
 'bife lomo porcion',
 'bife papa',
 'bife papa riquisima',
 'bife picana',
 'bife picana chorizo',
 'bife punto',
 'bife punto solicitado',
 'bit',
 'bit on',
 'bit on the',
 'bodegon',
 'bodegon boedo',
 'bodegon encantar',
 'bodegon encantar caber',
 'bodegon ruidoso',
 'bodegon ruidoso carta',
 'boedo',
 'bolichon',
 'bolichon cuarto',
 'bolichon cuarto comida',
 'boqueron',
 'boqueron verdura',
 'boqueron verdura ocurrar',
 'boscaiola',
 'boscaiola rico',
 'boscaiola rico abundante',
 'botella',
 'botella vino',
 'botella vino precio',
 'brindar',
 'brochette',
 'brochette langostino',
 'brochette langostino gusto',
 'brochettir',
 'brochettir punto',
 'brochettir punto bife',
 'buenisir',
 'buenisir cenamos',
 'buenisir cenamos matambrito',
 'buenooo',
 'buenooo rico',
 'buenooo rico ameno',
 'bullicio',
 'bullicio lugar',
 'bullicio lugar lujo',
 'bun',
 'bun encontrar',
 'bun encontrar bun',
 'bun relacion',
 'bun relacion precio',
 'buscador',
 'buscador recomendar',
 'buscador recomendar excelente',
 'buscar',
 'buscar mozo',
 'buscar mozo vista',
 'caber',
 'caber destacar',
 'caber destacar parrilla',
 'cabo',
 'cabo minuto',
 'cabo minuto chicle',
 'cadena',
 'cadena definitivamente',
 'cadena definitivamente sucursal',
 'caer',
 'caer el',
 'caer el mozo',
 'cafe',
 'cafe pagar',
 'cafe pagar 600',
 'cafe porcion',
 'cafe porcion abundante',
 'caipiroshka',
 'caipiroshka 390',
 'calamar',
 'calamar mejillon',
 'calamar mejillon boqueron',
 'calidad',
 'calidad acorde',
 'calidad acorde lugar',
 'calidad adecuado',
 'calidad adecuado atencion',
 'calidad ambiente',
 'calidad ambiente tranquilo',
 'calidad atencion',
 'calidad atencion costo',
 'calidad cantidad',
 'calidad cantidad porcion',
 'calidad cantidad precio',
 'calidad cantidad realidad',
 'calidad carne',
 'calidad carne achura',
 'calidad carne tierno',
 'calidad comida',
 'calidad comida recomendable',
 'calidad detalle',
 'calidad detalle pan',
 'calidad escribir',
 'calidad escribir mensaje',
 'calidad excelente',
 'calidad excelente parrillero',
 'calidad gente',
 'calidad gente especializar',
 'calidad idea',
 'calidad idea crayon',
 'calidad precio',
 'calidad precio 45',
 'calidad precio acorde',
 'calidad precio caro',
 'calidad producto',
 'calidad producto bun',
 'calidad valer',
 'calidad valer pena',
 'calido',
 'calido atencion',
 'calido atencion juntar',
 'calido excelente',
 'calido excelente calidad',
 'calient',
 'calient cubiertos',
 'calient cubiertos comida',
 'calient pedir',
 'calient pedir premium',
 'caliente',
 'caliente despu',
 'caliente despu ten',
 'calificacion',
 'calificacion mejoren',
 'calificacion mejoren vera',
 'camarera',
 'camarera lleno',
 'camarera lleno esperar',
 'camarero',
 'camarero pasar',
 'camarero pasar ayudante',
 'camaron',
 'camaron impecable',
 'camaron impecable bife',
 'cambiar',
 'cambiar mesa',
 'cambiar mesa reservar',
 'cambiar problema',
 'cambiar problema excelente',
 'cambio',
 'cambio plato',
 'cambio plato calient',
 'cantidad',
 'cantidad abundante',
 'cantidad abundante llevar',
 'cantidad asado',
 'cantidad asado lechon',
 'cantidad calidad',
 'cantidad calidad acorde',
 'cantidad gente',
 'cantidad gente rapido',
 'cantidad porcion',
 'cantidad porcion desmejorar',
 'cantidad precio',
 'cantidad precio atencion',
 'cantidad precio seguir',
 'cantidad realidad',
 'cantidad realidad pedir',
 'cantina',
 'cantina bolichon',
 'cantina bolichon cuarto',
 'capital',
 'capital atencion',
 'capital atencion 10',
 'capital gba',
 'capital gba alguien',
 'capres',
 'capres compartir',
 'capres compartir vino',
 'cara',
 'cara resumen',
 'cara resumen comida',
 'caracteristica',
 'caracteristica lineas',
 'caracteristica lineas general',
 'carisimar',
 'carisimar milanesa',
 'carisimar milanesa 98',
 'carne',
 'carne abundante',
 'carne abundante simpatico',
 'carne achura',
 'carne achura decair',
 'carne achura expectaculare',
 'carne cocido',
 'carne cocido sorpresa',
 'carne colita',
 'carne colita cuadril',
 'carne comentar',
 'carne comentar servico',
 'carne cosa',
 'carne cosa sugerir',
 'carne crudo',
 'carne crudo punto',
 'carne ensalada',
 'carne ensalada bebida',
 'carne frio',
 'carne frio molleja',
 'carne gomos',
 'carne gomos corte',
 'carne malo',
 'carne malo marcado',
 'carne nivel',
 'carne nivel buscar',
 'carne optimo',
 'carne optimo notar',
 'carne pollo',
 'carne pollo parrilla',
 'carne probar',
 'carne probar tiempo',
 'carne prober',
 'carne prober parrilla',
 'carne punto',
 'carne punto atencion',
 'carne riquisima',
 'carne riquisima opcion',
 'carne tierno',
 'carne tierno sabroso',
 'carne tortilla',
 'carne tortilla espanola',
 'caro',
 'caro comar',
 'caro comar atender',
 'caro dejar',
 'caro dejar pesimo',
 'caro malo',
 'caro malo calidad',
 'caro precio',
 'caro relacion',
 'caro relacion resto',
 'caro valer',
 'caro valer pena',
 'caro volver',
 'caro volver recomendable',
 'carta',
 'carta gigante',
 'carta gigante recomeir',
 'carta plato',
 'carta plato abundante',
 'carta postre',
 'carta postre esperar',
 'carta reducido',
 'carta reducido original',
 'carta vino',
 'carta vino cara',
 'carta vino faltar',
 'casa',
 'casa aceptable',
 'casa aceptable jueves',
 'casa comodo',
 'casa comodo agradable',
 'casero',
 'casero panqueques',
 'casero panqueques vigilante',
 'casero recien',
 'casero recien horneado',
 'casero sabrosisimos',
 'casero sabrosisimos tomatito',
 'casualidad',
 'casualidad grato',
 'casualidad grato sorpresa',
 'casualidad tocar',
 'casualidad tocar bife',
 'celiaco',
 'celiaco encontrar',
 'celiaco encontrar tipo',
 'cenabar',
 'cenabar reclamo',
 'cenabar reclamo punto',
 'cenamos',
 'cenamos matambrito',
 'cenamos matambrito pizza',
 'cenar',
 'cenar experiencia',
 'cenar experiencia pagar',
 'cenar mes',
 'cenar mes sorprender',
 'cenar persona',
 'cenar persona pedir',
 'cenar senora',
 'cenar senora comimos',
 'centavo',
 'cerca',
 'cerca parrilla',
 'cerca parrilla sali',
 'cerdo',
 'cerdo cm',
 'cerdo cm quemado',
 'cerrar',
 'cerrar salis',
 'cerrar salis podes',
 'cerveza',
 'cerveza tirado',
 'cerveza tirado comida',
 'cesar',
 'cesar pollo',
 'cesar pollo ten',
 'chaleco',
 'chaleco gritar',
 'chaleco gritar salir',
 'chaleco indicar',
 'chaleco indicar podiar',
 'champagne',
 'champagne masa',
 'champagne masa cafe',
 'champagne traer',
 'champagne traer comida',
 'chanta',
 'chanta creer',
 'chanta creer compruebenlo',
 'charlar',
 'charlar amigo',
 'charlar amigo principal',
 'cherrys',
 'cherrys confitado',
 'cherrys confitado aceituna',
 'chica',
 'chica cuidar',
 'chica cuidar plato',
 'chica estomago',
 'chica estomago contrario',
 'chica simpatico',
 'chica simpatico pasar',
 'chichulin',
 'chichulin ten',
 'chichulin ten papas',
 'chicle',
 'chicle costilla',
 'chicle costilla cordero',
 'chico',
 'chico calido',
 'chico calido excelente',
 'chico pagar',
 'chico pagar efectivo',
 'chico pequeno',
 'chico pequeno chica',
 'child',
 'child portion',
 'child portion the',
 'chimichurri',
 'chiquita',
 'chiquita rico',
 'chiquita rico barato',
 'choclo',
 'choclo huevo',
 'choclo huevo recomendado',
 'chocotorta',
 'chocotorta comer',
 'chocotorta comer persona',
 'chorizo',
 'chorizo argento',
 'chorizo argento tierno',
 'chorizo despu',
 'chorizo despu pedis',
 'chorizo duro',
 'chorizo duro 160',
 'chorizo especial',
 'chorizo especial ensalda',
 'chorizo morcilla',
 'chorizo morcilla chichulin',
 'chorizo morcilla fallo',
 'chorizo salsita',
 'chorizo salsita rico',
 'chorizo tradicional',
 'chorizo tradicional pequeno',
 'chorizo venir',
 'chorizo venir pedacito',
 'cine',
 'cine comida',
 'cine comida rico',
 'clasico',
 'clasico 70',
 'clasico costanera',
 'cliente',
 'cliente glumy',
 'cliente glumy ano',
 'cliente quedar',
 'cliente quedar desatisfecho',
 'clo',
 'clo pasa',
 'clo pasa momento',
 'cm',
 'cm quemado',
 'cm quemado solicitar',
 'cobrar',
 'cobrar aparte',
 'cobrar aparte hay',
 'cobrar perfecto',
 'cobrar perfecto incluir',
 'cobrar pesos',
 'cobrar pesos empanada',
 'cobrar servicio',
 'cobrar servicio mesa',
 'cobrarno',
 'cobrarno comenzar',
 'cobrarno comenzar declinacion',
 'cobro',
 'cobro aconsejar',
 'cobro aconsejar evitar',
 'coca',
 'coca agua',
 'coca agua vino',
 'coccion',
 'cocido',
 'cocido bajar',
 'cocido bajar calidad',
 'cocido cosa',
 'cocido cosa restaurante',
 'cocido mozo',
 'cocido mozo entender',
 'cocido salud',
 'cocido sorpresa',
 'cocido sorpresa carne',
 'cocido terminar',
 'cocido terminar comer',
 'cocinero',
 'cocinero argentino',
 'cocinero argentino desastre',
 'colita',
 'colita cuadril',
 'colita cuadril ojo',
 'comar',
 'comar atender',
 'comar atender barbaro',
 'comar atender hotel',
 'comar barra',
 'comar precio',
 'comar precio cosa',
 'comar precio logico',
 'combinacion',
 'combinacion sabor',
 'combinacion sabor plato',
 'comen',
 'comen volver',
 'comen volver aceptar',
 'comentamo',
 'comentamo frio',
 'comentamo frio rato',
 'comentar',
 'comentar culpa',
 'comentar culpa lugar',
 'comentar servico',
 'comentar servico desajustado',
 'comentarioos',
 'comentarioos groupon',
 'comentarioos groupon etnender',
 'comenzar',
 'comenzar declinacion',
 'comer',
 'comer 1000',
 'comer 1000 desilusionir',
 'comer aire',
 'comer aire libre',
 'comer amplificar',
 'comer amplificar ruido',
 'comer asado',
 'comer asado cortir',
 'comer atender',
 'comer cosa',
 'comer cosa mozo',
 'comer el',
 'comer el caro',
 'comer entrada',
 'comer entrada comimo',
 'comer familia',
 'comer familia carne',
 'comer familia relacion',
 'comer gastar',
 'comer horario',
 'comer horario 21',
 'comer novia',
 'comer novia ensalada',
 'comer pan',
 'comer pan estupendo',
 'comer parrilla',
 'comer parrilla principalmente',
 'comer persona',
 'comer persona antipasto',
 'comer semana',
 'comer semana noche',
 'comer sugerido',
 'comer sugerido mozo',
 'cometer',
 'cometer compesacion',
 'cometer compesacion error',
 'comi',
 'comi genial',
 'comi genial empanada',
 'comi grupo',
 'comi grupo error',
 'comi pagar',
 'comi pagar justo',
 'comi tirar',
 'comi tirar asado',
 'comi vida',
 'comi vida punto',
 'comida',
 'comida 17',
 'comida 17 comi',
 'comida abundante',
 'comida abundante brochettir',
 'comida abundante rico',
 'comida abundante salad',
 'comida aceptable',
 'comida aceptable compensar',
 'comida ambiente',
 'comida ambiente festivo',
 'comida ambiente insuperabl',
 'comida atencion',
 'comida atencion ambiente',
 'comida atencion calidad',
 'comida atencion precio',
 'comida bife',
 'comida bife lomo',
 'comida calidad',
 'comida calidad ambiente',
 'comida cantidad',
 'comida cantidad precio',
 'comida cantina',
 'comida cantina bolichon',
 'comida caro',
 'comida caro comar',
 'comida caro precio',
 'comida cerrar',
 'comida cerrar salis',
 'comida don',
 'comida don raro',
 'comida ecelente',
 'comida ecelente aperitivo',
 'comida elaborado',
 'comida ensalada',
 'comida ensalada aires',
 'comida espectacular',
 'comida espectacular acorde',
 'comida excelente',
 'comida excelente servicio',
 'comida general',
 'comida general porcion',
 'comida imperdonable',
 'comida imperdonable grupo',
 'comida impredible',
 'comida impredible ambientar',
 'comida maso',
 'comida maso lugar',
 'comida mundo',
 'comida mundo plato',
 'comida parrilla',
 'comida parrilla normal',
 'comida perfecto',
 'comida perfecto si',
 'comida porcion',
 'comida porcion enorme',
 'comida recomendable',
 'comida recomendable unico',
 'comida rico',
 'comida rico calidad',
 'comida rico general',
 'comida rico postre',
 'comida ropa',
 'comida ropa 100',
 'comida ruta',
 'comida sabroso',
 'comida sabroso carisimar',
 'comida servicio',
 'comida servicio ambiente',
 'comida servicio malo',
 'comida servir',
 'comida servir parrilla',
 'comida super',
 'comida super jardin',
 'comida tiempo',
 'comida tiempo moza',
 'comimo',
 'comimo ruculeta',
 'comimo ruculeta excelente',
 'comimos',
 'comimos festejamos',
 'comimos festejamos cumple',
 'comimos gustar',
 'comimos gustar lugar',
 'comimos lugar',
 'comimos lugar limpio',
 'comimos podiar',
 'comimos podiar precio',
 'comimos salmon',
 'comimos salmon rosado',
 'comodo',
 'comodo agradable',
 'comodo agradable ambiente',
 'comodo pulcritud',
 'comodo pulcritud lugar',
 'compartir',
 'compartir 200',
 'compartir 200 volver',
 'compartir agua',
 'compartir agua 66',
 'compartir aspecto',
 'compartir aspecto destacar',
 'compartir chocotorta',
 'compartir chocotorta comer',
 'compartir el',
 'compartir el persona',
 'compartir increible',
 'compartir increible risotto',
 'compartir ojo',
 'compartir ojo bife',

In [ ]:
count_df = pd.DataFrame(vectorized_data.toarray(), columns=vectorizer.get_feature_names_out(), index=df.index)
count_df

,03 precio,03 precio pagina,10,10 comida,10 comida impredible,10 persona,10 persona olvidar,100,100 bodegon,100 bodegon boedo,...,yo,yo irmir,yo irmir pagar,yo sobrar,yo sobrar inconveniente,zanahoria,zanahoria choclo,zanahoria choclo huevo,zona,zona creativo
8119,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
2036,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8758,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3475,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4418,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19048,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17963,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7902,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5723,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,1,0,0,0,0,0
7750,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(analyzer='word', ngram_range=(1, 2), min_df=0.001, max_df=0.9, strip_accents='ascii', max_features=2000)
vectorized_data = vectorizer.fit_transform(df['comentario'])

In [ ]:
vectorizer.get_feature_names_out()

array(['10', '10 comida', '10 persona', ..., 'which are', 'yo', 'zona'],
      dtype=object)

In [ ]:
tfidf_df = pd.DataFrame(vectorized_data.toarray(), columns=vectorizer.get_feature_names_out(), index=df.index)
tfidf_df

,10,10 comida,10 persona,100,100 bodegon,100 recomendable,1000,1000 desilusionir,107,107 milanesa,...,volver semana,volver sugerirl,voto,voto confianza,waiters,waiters friendly,which,which are,yo,zona
8119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.164199,0.164199,0.0,0.0,0.0,0.0,0.000000,0.133631
2036,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
8758,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
3475,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
4418,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19048,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
17963,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
7902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
5723,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.204253,0.000000
7750,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000