In [ ]:
import pandas as pd
pd.__version__

'2.2.2'

# Lectura y escritura de datos

In [ ]:
df = pd.read_csv("https://data.insideairbnb.com/argentina/ciudad-aut%C3%B3noma-de-buenos-aires/buenos-aires/2026-01-25/visualisations/listings.csv", index_col="id", parse_dates=["last_review"])
df.head()

,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
id,,,,,,,,,,,,,,,,,,
42610838,"Puerto Madero a 3 cuadras, centro, bello , tea...",224049389,1469188629918707060,Gabriela,NaN,San Nicolas,-34.599976,-58.374195,Entire home/apt,NaN,7.0,0,NaT,NaN,2,244,0,NaN
1305876403852901802,Apart estudio en Microcentro,25649070,1465347917068117288,Federico,NaN,San Nicolas,-34.600382,-58.372692,Entire home/apt,NaN,2.0,1,2025-01-18,0.08,1,307,0,NaN
1542233033640525302,"Departamento en Buenos Aires, abasto shopping",153014015,1468500000533080859,Marco,NaN,Balvanera,-34.603295,-58.409527,Entire home/apt,NaN,7.0,0,NaT,NaN,1,326,0,NaN
1004530078359434134,Departamento en Recoleta,1409800,1462517876404348407,Marian,NaN,Balvanera,-34.599230,-58.407060,Entire home/apt,NaN,1.0,22,2025-12-07,0.80,39,365,3,NaN
800145927121871422,Coqueto para 4 personas,467965425,1470109782901816721,Maria Del Carmen,NaN,Almagro,-34.599767,-58.426499,Entire home/apt,NaN,1.0,0,NaT,NaN,2,365,0,NaN

In [ ]:
df.dtypes

name                                      object
host_id                                    int64
host_profile_id                            int64
host_name                                 object
neighbourhood_group                      float64
neighbourhood                             object
latitude                                 float64
longitude                                float64
room_type                                 object
price                                    float64
minimum_nights                           float64
number_of_reviews                          int64
last_review                       datetime64[ns]
reviews_per_month                        float64
calculated_host_listings_count             int64
availability_365                           int64
number_of_reviews_ltm                      int64
license                                   object
dtype: object

# Limpieza de columnas

In [ ]:
df["name"] = df["name"].str.replace("★", "").str.replace("Depto", "Departamento")

In [ ]:
df["license"] = df["license"].fillna("no license")
#df["license"].fillna("no license", inplace=True)

In [ ]:
# quitar columnas: 2 formas equivalentes

df = df.drop(columns=["license"])
#df = df[df.columns.drop("license")]

# Discretización

In [ ]:
df["minimum_nights"].describe()

count    27242.000000
mean         4.748770
std         16.434273
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max        730.000000
Name: minimum_nights, dtype: float64

In [ ]:
# bins de igual longitud (q)
pd.qcut(df["minimum_nights"], q=3, labels=['short', 'medium', 'long'])#.value_counts()

minimum_nights
short     15415
long       6229
medium     5598
Name: count, dtype: int64

In [ ]:
# bins a mano
pd.cut(df["minimum_nights"], bins=[df["minimum_nights"].min(), 2, 4, df["minimum_nights"].max()], labels=['short', 'medium', 'long']).value_counts()

minimum_nights
short     7410
medium    7207
long      4620
Name: count, dtype: int64

# Numeración

In [ ]:
# mapeo
#df["room_type"].unique()
df["room_type"].map({"Entire home/apt": 1, "Private room": 2}) # si no está pone NaN // cambia tipo de dato

array(['Entire home/apt', 'Shared room', 'Private room', 'Hotel room'],
      dtype=object)

In [ ]:
# dummies
pd.get_dummies(df, columns=['neighbourhood'], dtype="int8") # , dummy_na=True

,name,host_id,host_profile_id,host_name,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,...,neighbourhood_Villa Gral. Mitre,neighbourhood_Villa Lugano,neighbourhood_Villa Luro,neighbourhood_Villa Ortuzar,neighbourhood_Villa Pueyrredon,neighbourhood_Villa Real,neighbourhood_Villa Riachuelo,neighbourhood_Villa Santa Rita,neighbourhood_Villa Soldati,neighbourhood_Villa Urquiza
id,,,,,,,,,,,,,,,,,,,,,
42610838,"Puerto Madero a 3 cuadras, centro, bello , tea...",224049389,1469188629918707060,Gabriela,NaN,-34.599976,-58.374195,Entire home/apt,NaN,7.0,...,0,0,0,0,0,0,0,0,0,0
1305876403852901802,Apart estudio en Microcentro,25649070,1465347917068117288,Federico,NaN,-34.600382,-58.372692,Entire home/apt,NaN,2.0,...,0,0,0,0,0,0,0,0,0,0
1542233033640525302,"Departamento en Buenos Aires, abasto shopping",153014015,1468500000533080859,Marco,NaN,-34.603295,-58.409527,Entire home/apt,NaN,7.0,...,0,0,0,0,0,0,0,0,0,0
1004530078359434134,Departamento en Recoleta,1409800,1462517876404348407,Marian,NaN,-34.599230,-58.407060,Entire home/apt,NaN,1.0,...,0,0,0,0,0,0,0,0,0,0
800145927121871422,Coqueto para 4 personas,467965425,1470109782901816721,Maria Del Carmen,NaN,-34.599767,-58.426499,Entire home/apt,NaN,1.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1587119060096878911,Estudio luminoso en el corazón de Villa Crespo.,1534662,1462518725032785871,Florencia,NaN,-34.597425,-58.442220,Entire home/apt,NaN,1.0,...,0,0,0,0,0,0,0,0,0,0
37623532,Modern Top located Duplex Apartment! Up to 4 pax,2809500,1462609256411099848,Florencia,NaN,-34.575020,-58.421840,Entire home/apt,NaN,30.0,...,0,0,0,0,0,0,0,0,0,0
1074846345919500333,Departamento Villa crespo I,133597828,1462947748907784667,Estudio H Apartments,NaN,-34.594473,-58.441314,Entire home/apt,NaN,2.0,...,0,0,0,0,0,0,0,0,0,0
1028342669639305203,"Depto a 8 min de Palermo,subte línea B 100 Mts.",49955010,1465763312015870684,Mariano,NaN,-34.600277,-58.437097,Entire home/apt,NaN,3.0,...,0,0,0,0,0,0,0,0,0,0
18517386,Apartment Full Equipment in Belgrano R,57658152,1466691284640462108,Ines,NaN,-34.568100,-58.456000,Entire home/apt,NaN,1.0,...,0,0,0,0,0,0,0,0,0,0

# Normalización

In [ ]:
(df["minimum_nights"] - df["minimum_nights"].min()) / (df["minimum_nights"].max() - df["minimum_nights"].min())

id
42610838               0.008230
1305876403852901802    0.001372
1542233033640525302    0.008230
1004530078359434134    0.000000
800145927121871422     0.000000
                         ...
1587119060096878911    0.000000
37623532               0.039781
1074846345919500333    0.001372
1028342669639305203    0.002743
18517386               0.000000
Name: minimum_nights, Length: 27348, dtype: float64

# Estandarización

In [ ]:
(df["minimum_nights"] - df["minimum_nights"].mean()) / df["minimum_nights"].std()

id
42610838               0.136984
1305876403852901802   -0.167258
1542233033640525302    0.136984
1004530078359434134   -0.228107
800145927121871422    -0.228107
                         ...
1587119060096878911   -0.228107
37623532               1.536498
1074846345919500333   -0.167258
1028342669639305203   -0.106410
18517386              -0.228107
Name: minimum_nights, Length: 27348, dtype: float64